
services:
  bot:
    build: .
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - MONGO_URI=${MONGO_URI}
      - ADMIN_IDS=${ADMIN_IDS}
    depends_on:
      - mongodb
    networks:
      - botnet

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongodb_data:/data/db
    networks:
      - botnet

volumes:
  mongodb_data:

networks:
  botnet:
